from controlled_values_lists import *

fieldIndex = {
 1: {'mandate': True, 'repeat': False,
     'attr': {'con': 'DOI', 'ele': 'identifierType'},
     'child': '',
     'ele': 'identifier'},
 2: {'mandate': True, 'repeat': True,
     'attr': '',
     'child': {'attr': '',
               'child': [{'attr': {'con': nameType, 'ele': 'nameType'},
                          'child': '',
                          'ele': 'creatorName'},
                         {'attr': '',
                          'child': '',
                          'ele': 'givenName'},
                         {'attr': '',
                          'child': '',
                          'ele': 'familyName'},
                         {'attr': [{'con': nameIdentifierScheme, 'ele': 'nameIdentifierScheme'},
                                   {'con': schemeURI, 'ele': 'schemeURI'}],
                          'child': '',
                          'ele': 'nameIdentifier'},
                         {'attr': '',
                          'child': '',
                          'ele': 'affiliation'}],
               'ele': 'creator'},
     'ele': 'creators'},
 3: {'mandate': True, 'repeat': True,
     'attr': '',
     'child': {'attr': {'con': titleType, 'ele': 'titleType'}, 'child': '', 'ele': 'title'},
     'ele': 'titles'},
 4: {'mandate': True, 'repeat': False, 'attr': '', 'child': '', 'ele': 'publisher'},
 5: {'mandate': True, 'repeat': False, 'attr': '', 'child': '', 'ele': 'publicationYear'},
 6: {'mandate': False, 'repeat': True, 'attr': '',
     'child': {'attr': [{'con': '', 'ele': 'subjectScheme'},
                        {'con': '', 'ele': 'schemeURI'},
                        {'con': '', 'ele': 'valueURI'}],
               'child': '',
               'ele': 'subject'},
     'ele': 'subjects'},
 7: {'mandate': False, 'repeat': True,
     'attr': '',
     'child': {'attr': {'con': contributorType, 'ele': 'contributorType'},
               'child': [{'attr': {'con': nameType, 'ele': 'nameType'},
                          'child': '',
                          'ele': 'contributorName'},
                         {'attr': '',
                          'child': '',
                          'ele': 'givenName'},
                         {'attr': '',
                          'child': '',
                          'ele': 'familyName'},
                         {'attr': [{'con': nameIdentifierScheme, 'ele': 'nameIdentifierScheme'},
                                   {'con': schemeURI, 'ele': 'schemeURI'}],
                          'child': '',
                          'ele': 'nameIdentifier'},
                         {'attr': '',
                          'child': '',
                          'ele': 'affiliation'}],
               'ele': 'contributor'},
     'ele': 'contributors'},
 8: {'mandate': False, 'repeat': True,
     'attr': '',
     'child': {'attr': [{'con': dateType, 'ele': 'dateType'},
                        {'con': '', 'ele': 'dateInformation'}],
               'child': '',
               'ele': 'date'},
     'ele': 'dates'},
 9: {'mandate': False, 'repeat': False, 'attr': '', 'child': '', 'ele': 'language'},
 10: {'mandate': True, 'repeat': False,
      'attr': {'con': resourceTypeGeneral, 'ele': 'resourceTypeGeneral'},
      'child': '',
      'ele': 'resourceType'},
 11: {'mandate': False, 'repeat': True, 'attr': '',
      'child': {'attr': {'con': '', 'ele': 'alternateIdentifierType'},
                'child': '',
                'ele': 'alternateIdentifier'},
      'ele': 'alternateIdentifiers'},
 12: {'mandate': False, 'repeat': True, 'attr': '',
      'child': {'attr': [{'con': relatedIdentifierType, 'ele': 'relatedIdentifierType'},
                         {'con': relationType, 'ele': 'relationType'},
                         {'con': '', 'ele': 'relatedMetadataScheme'},
                         {'con': '', 'ele': 'schemeURI'},
                         {'con': '', 'ele': 'schemeType'},
                         {'con': resourceTypeGeneral, 'ele': 'resourceTypeGeneral'}],
                'child': '',
                'ele': 'relatedIdentifier'},
      'ele': 'relatedIdentifiers'},
 13: {'mandate': False, 'repeat': True, 'attr': '',
      'child': {'attr': '', 'child': '', 'ele': 'size'}, 'ele': 'sizes'},
 14: {'mandate': False, 'repeat': True, 'attr': '',
      'child': {'attr': '', 'child': '', 'ele': 'format'}, 'ele': 'formats'},
 15: {'mandate': False, 'repeat': False, 'attr': '', 'child': '', 'ele': 'version'},
 16: {'mandate': False, 'repeat': True, 'attr': '',
      'child': {'attr': {'con': '', 'ele': 'rightsURI'},
                'child': '',
                'ele': 'rights'},
      'ele': 'rightsList'},
 17: {'mandate': False, 'repeat': True, 'attr': '',
      'child': {'attr': {'con': descriptionType, 'ele': 'descriptionType'},
                'child': '',
                'ele': 'description'},
      'ele': 'descriptions'},
 18: {'mandate': False, 'repeat': True, 'attr': '',
      'child': {'attr': '',
                'child': [{'attr': '', 'child': '', 'ele': 'geoLocationPlace'},
                          {'attr': '',
                           'child': [{'attr': '', 'child': '', 'ele': 'pointLongitude'},
                                     {'attr': '', 'child': '', 'ele': 'pointLatitude'}],
                           'ele': 'geoLocationPoint'},
                          {'attr': '',
                           'child': [{'attr': '', 'child': '', 'ele': 'westBoundLongitude'},
                                     {'attr': '', 'child': '', 'ele': 'eastBoundLongitude'},
                                     {'attr': '', 'child': '', 'ele': 'northBoundLatitude'},
                                     {'attr': '', 'child': '', 'ele': 'southBoundLatitude'}],
                           'ele': 'geoLocationBox'},
                          {'attr': '',
                           'child': {'attr': '',
                                     'child': [{'attr': '', 'child': '', 'ele': 'pointLongitude'},
                                               {'attr': '', 'child': '', 'ele': 'pointLatitude'}],
                                     'ele': 'polygonPoint'},
                           'ele': 'geoLocationPolygon'}],
                'ele': 'geoLocation'},
      'ele': 'geoLocations'},
 19: {'mandate': False, 'repeat': True, 'attr': '',
      'child': {'attr': '',
                'child': [{'attr': '','child': '', 'ele': 'funderName'},
                          {'attr': {'con': funderIdentifierType,
                                    'ele': 'funderIdentifierType'},
                           'child': '',
                           'ele': 'funderIdentifier'},
                          {'attr': '',
                            'child': '',
                            'ele': 'awardNumber'},
                          {'attr': '',
                            'child': '',
                            'ele': 'awardURI'},
                          {'attr': '',
                            'child': '',
                            'ele': 'awardTitle'}
                          ],
                'ele': 'fundingReference'},
      'ele': 'fundingReferences'}}

values_num = {
 2: 5,
 3: 2,
 6: 4,
 7: 6,
 8: 3,
 11: 2,
 12: 7,
 16: 2,
 17: 2,
 19: 6}
